extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
plugins:
  - "@typescript-eslint"
  - eslint-plugin-prettier
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: ./tsconfig.json
rules:
  eqeqeq: error
  no-console:
    - error
    - allow:
      - warn
      - error
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": error
  no-var: error
  prettier/prettier:
    - error
    - trailingComma: all
      singleQuote: true