import { SideMenu } from '@/components/parts/SideMenu';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="container flex">
          <aside>
            <SideMenu></SideMenu>
          </aside>
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
